=== miszekb/XML_Projects/Zadanie 2/generated_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dokument">
    <xs:annotation>
      <xs:documentation>XML Car Database created by Michał Mamona &amp; Michał Białecki [2019]</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autorzy">
          <xs:annotation>
            <xs:documentation>&lt;info>
			Przeglądasz obecnie bazę samochodów wraz z ich podstawowymi parametrami
			sporządzoną w ramach przedmiotu "Programowanie Komunikacji Człowiek-Komputer".
			Dane pochodzą z serwisu z ogłoszeniami otomoto.pl
		&lt;/info></xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="autor" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="grupa_TGSK" use="optional"/>
                      <xs:attribute type="xs:string" name="github" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="zmiany">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="zmiana" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="baza">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="samochód" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="marka_auta">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="markaID" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="model">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="kraj" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:short" name="rocznik"/>
                    <xs:element type="xs:string" name="typ"/>
                    <xs:element type="xs:int" name="przebieg"/>
                    <xs:element type="xs:string" name="rodzaj_silnika"/>
                    <xs:element type="xs:string" name="pojemność_silnika"/>
                    <xs:element type="xs:int" name="cena"/>
                    <xs:element type="xs:date" name="data_umieszczenia_ogłoszenia"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="ID" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="marki">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="marka" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="koncern"/>
                    <xs:element type="xs:short" name="rok_założenia"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="markaID" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miszekb/XML_Projects/Zadanie 3/car_database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/css" href="styles.css" ?>-->
<?xml-stylesheet type="text/xsl" href="car_database.xsl" ?>

<!-- <!DOCTYPE dokument SYSTEM "car_database.dtd"> -->
<!-- XML Car Database created by Michał Mamona & Michał Białecki [2019]-->
<dokument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generated_schema.xsd">
<!--		<info>
			Przeglądasz obecnie bazę samochodów wraz z ich podstawowymi parametrami
			sporządzoną w ramach przedmiotu "Programowanie Komunikacji Człowiek-Komputer".
			Dane pochodzą z serwisu z ogłoszeniami otomoto.pl
		</info> -->
	<autorzy>
			<autor grupa_TGSK="2" github="MickAlmighty">Michał Mamona 210266</autor>
			<autor grupa_TGSK="1" github="miszekb">Michał Białecki 210141</autor>
	</autorzy>
	<zmiany>
			<zmiana>2019-03-04 09:54 PM</zmiana>
			<zmiana>2019-03-05 12:57 AM</zmiana>
			<zmiana>2019-03-07 01:16 AM</zmiana>
			<zmiana>2019-03-07 10:47 AM</zmiana>
	</zmiany>
		<baza>
		<samochód ID="auto1">
			<marka_auta markaID="M1"/>
			<model kraj="Niemcy">Sharan</model>
			<rocznik>2008</rocznik>
			<typ>Minivan</typ>
			<przebieg jednostki="km">248000</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>1.8</pojemność_silnika>
			<cena waluta="PLN">26700</cena>
			<data_umieszczenia_ogłoszenia>2018-12-30</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto2">
			<marka_auta markaID="M3"/>
			<model kraj="Japonia">Auris</model>
			<rocznik>2016</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">59500</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>1.6</pojemność_silnika>
			<cena waluta="PLN">52900</cena>
			<data_umieszczenia_ogłoszenia>2018-11-27</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto3">
			<marka_auta markaID="M4"/>
			<model kraj="Niemcy">A4</model>
			<rocznik>2018</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">1</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>3.2</pojemność_silnika>
			<cena waluta="PLN">165914</cena>
			<data_umieszczenia_ogłoszenia>2018-10-19</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto4">
			<marka_auta markaID="M2"/>
			<model kraj="Niemcy">X6</model>
			<rocznik>2008</rocznik>
			<typ>SUV</typ>
			<przebieg jednostki="km">110000</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>4.0</pojemność_silnika>
			<cena waluta="PLN">89900</cena>
			<data_umieszczenia_ogłoszenia>2019-02-04</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto5">
			<marka_auta markaID="M5"/>
			<model kraj="Wielka_Brytania">Cooper S</model>
			<rocznik>2007</rocznik>
			<typ>Auta małe</typ>
			<przebieg jednostki="km">150000</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>0.8</pojemność_silnika>
			<cena waluta="PLN">30000</cena>
			<data_umieszczenia_ogłoszenia>2019-03-03</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto6">
			<marka_auta markaID="M15"/>
			<model kraj="Włochy">Giulietta</model>
			<rocznik>2012</rocznik>
			<typ>Kompakt</typ>
			<przebieg jednostki="km">144000</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>1.2</pojemność_silnika>
			<cena waluta="PLN">41800</cena>
			<data_umieszczenia_ogłoszenia>2018-11-25</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto7">
			<marka_auta markaID="M1"/>
			<model kraj="Niemcy">Touareg</model>
			<rocznik>2010</rocznik>
			<typ>SUV</typ>
			<przebieg jednostki="km">367862</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>3.5</pojemność_silnika>
			<cena waluta="PLN">59500</cena>
			<data_umieszczenia_ogłoszenia>2019-02-07</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto8">
			<marka_auta markaID="M6"/>
			<model kraj="Wielka_Brytania">F-Pace</model>
			<rocznik>2018</rocznik>
			<typ>SUV</typ>
			<przebieg jednostki="km">5500</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>5.0</pojemność_silnika>
			<cena waluta="PLN">230000</cena>
			<data_umieszczenia_ogłoszenia>2019-01-23</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto9">
			<marka_auta markaID="M17"/>
			<model kraj="USA">Grand Cherokee IV</model>
			<rocznik>2011</rocznik>
			<typ>SUV</typ>
			<przebieg jednostki="km">196000</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>5.5</pojemność_silnika>
			<cena waluta="PLN">649000</cena>
			<data_umieszczenia_ogłoszenia>2018-12-22</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto10">
			<marka_auta markaID="M18"/>
			<model kraj="Włochy">Magirus</model>
			<rocznik>1984</rocznik>
			<typ>Tir</typ>
			<przebieg jednostki="km">436581</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>7.0</pojemność_silnika>
			<cena waluta="PLN">29000</cena>
			<data_umieszczenia_ogłoszenia>2018-09-12</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto11">
			<marka_auta markaID="M13"/>
			<model kraj="Czechy">Fabia II</model>
			<rocznik>2013</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">167000</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>1.3</pojemność_silnika>
			<cena waluta="PLN">22555</cena>
			<data_umieszczenia_ogłoszenia>2019-03-04</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto12">
			<marka_auta markaID="M4"/>
			<model kraj="Niemcy">A6 C6</model>
			<rocznik>2010</rocznik>
			<typ>Sedan</typ>
			<przebieg jednostki="km">162000</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>5.2</pojemność_silnika>
			<cena waluta="PLN">45900</cena>
			<data_umieszczenia_ogłoszenia>2018-11-28</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto13">
			<marka_auta markaID="M12"/>
			<model kraj="Japonia">6 III</model>
			<rocznik>2014</rocznik>
			<typ>Sedan</typ>
			<przebieg jednostki="km">223000</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>3.8</pojemność_silnika>
			<cena waluta="PLN">49500</cena>
			<data_umieszczenia_ogłoszenia>2019-02-01</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto14">
			<marka_auta markaID="M16"/>
			<model kraj="Japonia">Qashqai II</model>
			<rocznik>2018</rocznik>
			<typ>SUV</typ>
			<przebieg jednostki="km">1</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>2.9</pojemność_silnika>
			<cena waluta="PLN">91900</cena>
			<data_umieszczenia_ogłoszenia>2018-12-09</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto15">
			<marka_auta markaID="M14"/>
			<model kraj="Niemcy">Astra K</model>
			<rocznik>2018</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">1</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>2.5</pojemność_silnika>
			<cena waluta="PLN">99900</cena>
			<data_umieszczenia_ogłoszenia>2019-03-05</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto16">
			<marka_auta markaID="M19"/>
			<model kraj="Niemcy">TGX</model>
			<rocznik>2015</rocznik>
			<typ>Tir</typ>
			<przebieg jednostki="km">400000</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>8.1</pojemność_silnika>
			<cena waluta="PLN">120500</cena>
			<data_umieszczenia_ogłoszenia>2018-10-30</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto17">
			<marka_auta markaID="M1"/>
			<model kraj="Niemcy">Caravelle</model>
			<rocznik>2018</rocznik>
			<typ>Minivan</typ>
			<przebieg jednostki="km">7</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>3.4</pojemność_silnika>
			<cena waluta="PLN">108060</cena>
			<data_umieszczenia_ogłoszenia>2019-02-21</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto18">
			<marka_auta markaID="M10"/>
			<model kraj="Korea">Optima</model>
			<rocznik>2015</rocznik>
			<typ>Sedan</typ>
			<przebieg jednostki="km">109870</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>3.1</pojemność_silnika>
			<cena waluta="PLN">58000</cena>
			<data_umieszczenia_ogłoszenia>2018-11-26</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto19">
			<marka_auta markaID="M11"/>
			<model kraj="Japonia">Legacy IV</model>
			<rocznik>2008</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">294500</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>3.5</pojemność_silnika>
			<cena waluta="PLN">24900</cena>
			<data_umieszczenia_ogłoszenia>2019-02-09</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto20">
			<marka_auta markaID="M8"/>
			<model kraj="Włochy">500</model>
			<rocznik>2013</rocznik>
			<typ>Auta małe</typ>
			<przebieg jednostki="km">26556</przebieg>
			<rodzaj_silnika>Elektryczny</rodzaj_silnika>
			<pojemność_silnika>0.0</pojemność_silnika>
			<cena waluta="PLN">68900</cena>
			<data_umieszczenia_ogłoszenia>2018-12-21</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto21">
			<marka_auta markaID="M20"/>
			<model kraj="USA">Camaro</model>
			<rocznik>2013</rocznik>
			<typ>Coupe</typ>
			<przebieg jednostki="km">94901</przebieg>
			<rodzaj_silnika>Benzyna</rodzaj_silnika>
			<pojemność_silnika>5.3</pojemność_silnika>
			<cena waluta="PLN">49999</cena>
			<data_umieszczenia_ogłoszenia>2018-08-25</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto22">
			<marka_auta markaID="M14"/>
			<model kraj="Niemcy">Insignia B</model>
			<rocznik>2017</rocznik>
			<typ>Kombi</typ>
			<przebieg jednostki="km">42600</przebieg>
			<rodzaj_silnika>Diesel</rodzaj_silnika>
			<pojemność_silnika>2.6</pojemność_silnika>
			<cena waluta="PLN">91900</cena>
			<data_umieszczenia_ogłoszenia>2019-03-06</data_umieszczenia_ogłoszenia>
		</samochód>
		<samochód ID="auto23">
			<marka_auta markaID="M8"/>
			<model kraj="Włochy">Diablo II</model>
			<rocznik>2016</rocznik>
			<typ>Minivan</typ>
